In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("1. Empty array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4X2
ones_array = np.ones((4, 2))
print("\n2. All ones array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
filled_array = np.full((3, 3), 7)  # A 3x3 array filled with the value 7
print("\n3. Array filled with value 7 (3x3):\n", filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
zeros_like_array = np.zeros_like(filled_array)
print("\n4. Zeros array with same shape as filled_array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(filled_array)
print("\n5. Ones array with same shape as filled_array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted numpy array:\n", numpy_array)



1. Empty array (2x2):
 [[4.77004267e-310 0.00000000e+000]
 [9.04115220e+271 1.02124020e+277]]

2. All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array with same shape as filled_array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones array with same shape as filled_array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

6. Converted numpy array:
 [1 2 3 4]


In [ ]:
import numpy as np
# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("\n1. Array with values ranging from 10 to 49:\n", array_range)

# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix with values 0 to 8:\n", matrix_3x3)

# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. 10x10 array with random values:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero array with 5th element replaced with 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\n7. Reversed array:\n", reversed_array)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:\n", checkerboard)



1. Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
 [0.29011008 0.08170477 0.05650098 0.08086917 0.31284067 0.78753587
 0.66068138 0.23022889 0.22245806 0.10835481 0.73196507 0.86096279
 0.67297713 0.91486791 0.78760797 0.0339124  0.93410386 0.75789518
 0.34746144 0.6729805  0.42984973 0.94703214 0.55674595 0.98838273
 0.95432148 0.7021483  0.09274822 0.91379854 0.88653058 0.57234225]
Mean of the array: 0.5529972951391761

5. 10x10 array with random values:
 [[0.18568924 0.22482147 0.64557575 0.60608227 0.20369618 0.94238696
  0.2461421  0.89656197 0.92981926 0.96053215]
 [0.30233282 0.18390726 0.37180286 0.47826385 0.48744634 0.64093241
  0.19870694 0.13347383 0.0204797  0.7431066 ]
 [0.4662162  0.92419375 0.2617876

In [ ]:
import numpy as np
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11,12])
ares = x+y
print(ares)

[[ 6  8]
 [10 13]]


In [ ]:
sub = x-y
print(sub)

[[-4 -4]
 [-4 -3]]


In [ ]:
#multiply the array with any integers
mulx = x * 2
muly = y * 4
print(mulx)
print(muly)

[[ 2  4]
 [ 6 10]]
[[20 24]
 [28 32]]


In [ ]:
# find the square of each element
xs = np.square(x)
ys = np.square(y)
print(xs)
print(ys)

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]


In [ ]:
# find the dot product between v and w, x and v, x and y
vw = np.dot(v,w)
print("\nv and w",vw)
xv = np.dot(x,v)
print("\n x and v",xv)
xy = np.dot(x,y)
print("\n x and y",x,y)


v and w 219

 x and v [29 77]

 x and y [[1 2]
 [3 5]] [[5 6]
 [7 8]]


In [ ]:
# concatinate x and y along row and concat v and w along column
concat_xy = np.concatenate((x,y), axis = 0)
print("\n concat x and y: ", concat_xy)
concat_vw = np.vstack((v,w)).T
print("\n concat v and w",concat_vw)


 concat x and y:  [[1 2]
 [3 5]
 [5 6]
 [7 8]]

 concat v and w [[ 9 11]
 [10 12]]


In [ ]:
concat_xv = np.concatenate((x,v), axis = 0)
# error because x is a 2*2 matrix while v is 1*2.
# x is 2 dimensional v is 1.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
# prblm 4
import numpy as np
a = np.array([[3,4], [7,8]])
b = np.array([[5,3], [2,1]])
# A*A-1 = I
inverse_A = np.linalg.inv(a)
identity = np.dot(a, inverse_A)
print(identity)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
# AB != BA
ab = np.dot(a,b)
ba = np.dot(b,a)
print("A*B = \n", ab)
print("B*A = \n", ba)

A*B = 
 [[23 13]
 [51 29]]
B*A = 
 [[36 44]
 [13 16]]


In [ ]:
# Bt*At = (AB)t
b_trans = np.transpose(b)
a_trans = np.transpose(a)
ab_trans = np.transpose(ab)
aTbT_trans = np.dot(b_trans, a_trans)
print("At*Bt = \n", aTbT_trans)
print("(A*B)t = \n", ab_trans)

At*Bt = 
 [[23 51]
 [13 29]]
(A*B)t = 
 [[23 51]
 [13 29]]


In [ ]:
# inverse method
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

m1 = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
c1 = np.array([-1, -3, 9])
# a inverse
m1_inverse = np.linalg.inv(m1)
x = np.dot(m1_inverse, c1)
x,y,z = x
print("x = ", x)
print("y = ", y)
print("z = ", z)

x =  2.0
y =  1.0
z =  -2.0


In [ ]:
import numpy as np
# matrix creation
a1 = np.array([[3,4,5],[6,7,8], [3,4,5]])
print(a1)
# empty array
e1 = np.empty((2,2))
print(e1)
# ones array
o1 = np.ones((4,2))
print(o1)
# fill array
f1 = np.full((3,3),3)
print(f1)
# zero array with the same type
a1 = np.array([[3,4, 5], [6,7, 8], [9,0,1]])
z1 = np.zeros_like(a1)
print(z1)
# ones array with same type
o2 = np.ones_like(a1)
print(o2)
# list into array
l1 = [1,2,3,4]
arr1 = np.array(l1)
print(arr1)
# array with certain range
range = np.arange(10,51)
print(range)
# 3*3 array with certain va;ue
ar1 = np.arange(9).reshape((3,3))
print(ar1)
# identity
iden = np.eye(3)
print(iden)
rad_array = np.random.random(30)
mean = np.mean(rad_array)
print(rad_array)
print("mean: ", mean)
ran = np.random.random((10,10))
min = np.min(ran)
max = np.max(ran)
print("min: ", min)
print("max: ", max)

[[3 4 5]
 [6 7 8]
 [3 4 5]]
[[2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 2 3 4]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.61603437 0.16994522 0.32944848 0.20679254 0.66571706 0.05748211
 0.74966034 0.53988506 0.92879685 0.85719556 0.97476461 0.46773386
 0.19965974 0.18130659 0.79400387 0.40790501 0.49928998 0.41477482
 0.81751324 0.84942486 0.98067697 0.80863607 0.70077549 0.50377849
 0.67098602 0.43919798 0.59717281 0.67496223 0.13601149 0.81628048]
mean:  0.5685270739749883
min:  0.014955116052960626
max:  0.9897456507077497
